[variables]
PHP_VERSION = "8.1"

[phases.setup]
nixPkgs = [
    "php81",
    "php81Extensions.mbstring",
    "php81Extensions.pdo_mysql", 
    "php81Extensions.pdo_pgsql",
    "php81Extensions.gd",
    "php81Extensions.zip",
    "php81Extensions.redis",
    "php81Extensions.bcmath",
    "php81Extensions.intl",
    "php81Extensions.exif",
    "php81Extensions.pcntl",
    "php81Extensions.ctype",
    "php81Extensions.curl",
    "php81Extensions.dom",
    "php81Extensions.fileinfo",
    "php81Extensions.filter",
    "php81Extensions.hash",
    "php81Extensions.openssl",
    "php81Extensions.pcre",
    "php81Extensions.pdo",
    "php81Extensions.session",
    "php81Extensions.tokenizer",
    "php81Extensions.xml"
]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-scripts --no-interaction --ignore-platform-req=ext-gd"
]

[phases.build] 
cmds = [
    "php artisan config:cache",
    "php artisan route:cache", 
    "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"